# Generated by Django 2.2.2 on 2019-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20190617_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remise',
            field=models.IntegerField(default=0),
        ),
    ]
